import { type NextPage } from "next";
import Head from "next/head";
import Podcasts from "./podcasts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lore Podcast</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Podcasts />
    </>
  );
};

export default Home;
